version: '3.8'

services:
  app:
    container_name: akiba
    restart: on-failure
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - database

  database:
    image: 'postgres:alpine'
    container_name: akiba-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "almond"
      POSTGRES_PASSWORD: "almond"
      POSTGRES_DB: "almond"
    ports:
      - "5420:5432"